# Site settings
title: tolpp.com
email: ahmettolgaokur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tolpp.com; algoritmalara, veri yapılarına, bilgisayarla çözülebilecek problemlere yer verilen bir blogdur.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://tolpp.github.com" # the base hostname & protocol for your site
twitter_username: tolpp
github_username:  tolpp

# Build settings
markdown: kramdown
permalink: /:title/

gems:
  - jekyll-sitemap
