# Site settings
title: tolpp.com
title_description: yazılım ve programlama günlüğü
email: ahmettolgaokur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  tolpp.com; algoritmalara, veri yapılarına, bilgisayarla çözülebilecek problemlere yer verilen bir blogdur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://tolpp.com" # the base hostname & protocol for your site
twitter_username: tolpp
github_username:  tolpp

# Build settings
markdown: kramdown
permalink: /:title/

minify_html: false

## Tagging
tag_page_layout: tag_page
tag_page_dir: tag

#tag_feed_layout: tag_feed
#tag_feed_dir: tag

ignored_tags: [ignored] #ignored tags should be here

gems:
  - jekyll-sitemap
  - octopress-minify-html
